FROM python:3.13.3-slim

ENV TZ="Europe/Brussels"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /course_maker
COPY requirements.txt /course_maker/
RUN pip install -r requirements.txt
COPY . /course_maker/

ENV DATABASE_URL ""
ENV SECRET_KEY "non-secret-key-for-building-purposes"
RUN python manage.py collectstatic --noinput

EXPOSE 8000
CMD python main.py