# Generated by Django 5.2.6 on 2025-09-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient', to='ingredient.typeingredient'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='ingredients',
            field=models.ManyToManyField(related_name='recettes', to='ingredient.ingredient'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='typeingredient',
            name='name',
            field=models.CharField(),
        ),
    ]
