# Generated by Django 5.2.6 on 2025-10-03 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='list',
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='shopping_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredient.shoppinglist'),
            preserve_default=False,
        ),
    ]
