# Generated by Django 5.2.6 on 2025-10-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_remove_shoppinglistitem_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='shopping_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredient.shoppinglist'),
        ),
    ]
