# Generated by Django 5.2.6 on 2025-09-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_alter_ingredient_name_alter_ingredient_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recette',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='typeingredient',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
