# Generated by Django 5.2.6 on 2025-10-04 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_alter_shoppinglistitem_shopping_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_families', to='ingredient.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredient.recipetype'),
            preserve_default=False,
        ),
    ]
